In [1]:
import pandas as pd
from pathlib import Path
from functools import reduce
import numpy as np

In [2]:
# Load the dataset created in the data collection step
processed_dir = Path("D:\Erdos\Data Science Bootcamp\early_diabetes_screening\data\processed")
df_clean_before_targetdrop = pd.read_csv(processed_dir / "clean_project_dataset_before_targetdrop.csv")
df_clean = pd.read_csv(processed_dir / "clean_project_dataset.csv")
df_clean.head()

,SEQN,RIDAGEYR,RIAGENDR,RIDRETH3,DMDEDUC2,INDFMPIR,BMXBMI,BMXWAIST,BPXOSY1,BPXOSY2,...,ALQ111,ALQ121,ALQ130,DBQ700,DBD895,DBD900,DBD905,DBD910,doctor_diabetes,diabetes
0,109266.0,29.0,2.0,6.0,5.0,5.00,37.8,117.9,99.0,99.0,...,1.0,1.000000e+01,1.0,3.0,7.000000e+00,5.397605e-79,5.397605e-79,5.000000e+00,0.0,0
1,109267.0,21.0,2.0,2.0,4.0,5.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,4.000000e+00,5.397605e-79,5.397605e-79,5.397605e-79,0.0,0
2,109271.0,49.0,1.0,3.0,2.0,NaN,29.7,120.4,102.0,108.0,...,1.0,5.397605e-79,NaN,3.0,2.000000e+00,2.000000e+00,5.397605e-79,5.397605e-79,0.0,0
3,109273.0,36.0,1.0,3.0,4.0,0.83,21.9,86.8,116.0,110.0,...,1.0,5.397605e-79,NaN,4.0,2.000000e+00,2.000000e+00,5.397605e-79,7.000000e+00,0.0,0
4,109274.0,68.0,1.0,7.0,4.0,1.20,30.2,109.6,138.0,132.0,...,1.0,4.000000e+00,2.0,2.0,5.397605e-79,NaN,5.397605e-79,5.397605e-79,1.0,1

In [3]:
#check granularity - each row of the dataset represent one participant
print("Unique participants number:", df_clean["SEQN"].nunique())
print("Total number of rows:", len(df_clean))
print("Duplicate SEQN rows:", df_clean["SEQN"].duplicated().sum())

Unique participants number: 9232
Total number of rows: 9232
Duplicate SEQN rows: 0

In [8]:
# volume, coverage and representativeness
print("Dataset size:", df_clean.shape)

df_clean["RIDAGEYR"].describe()

df_clean["RIAGENDR"].value_counts() #1-male and 2-female 
df_clean["RIAGENDR"].value_counts(normalize=True) * 100

df_clean["RIDRETH3"].value_counts()
df_clean["RIDRETH3"].value_counts(normalize=True)*100

df_clean["DMDEDUC2"].value_counts()
df_clean["DMDEDUC2"].value_counts(normalize=True)*100

Dataset size: (9232, 37)

DMDEDUC2
4.0    32.277314
5.0    24.487360
3.0    24.140176
2.0    11.294347
1.0     7.800803
Name: proportion, dtype: float64

In [96]:
pd.crosstab(df_clean["RIDAGEYR"], df_clean["diabetes"], margins=True)

diabetes     0     1   All
RIDAGEYR
20.0       121     1   122
21.0       126     0   126
22.0       143     2   145
23.0       147     3   150
24.0       138     4   142
...        ...   ...   ...
77.0        47    34    81
78.0        43    26    69
79.0        41    28    69
80.0       483   199   682
All       7412  1820  9232

[62 rows x 3 columns]

In [97]:
pd.crosstab(df_clean["RIAGENDR"], df_clean["diabetes"], margins=True)

diabetes     0     1   All
RIAGENDR
1.0       3523   956  4479
2.0       3889   864  4753
All       7412  1820  9232

In [98]:
pd.crosstab(df_clean["RIDRETH3"], df_clean["diabetes"], margins=True)

diabetes     0     1   All
RIDRETH3
1.0        818   239  1057
2.0        740   200   940
3.0       2658   559  3217
4.0       1934   525  2459
6.0        911   209  1120
7.0        351    88   439
All       7412  1820  9232

In [99]:
pd.crosstab(df_clean["DMDEDUC2"], df_clean["diabetes"], margins=True)

diabetes     0     1   All
DMDEDUC2
1.0        482   237   719
2.0        793   248  1041
3.0       1774   451  2225
4.0       2431   544  2975
5.0       1920   337  2257
All       7400  1817  9217

In [100]:
df_clean["DMDEDUC2"].isna().sum()

np.int64(15)

In [101]:
print("Before target cleaning:", df_clean_before_targetdrop.shape)
print("After target cleaning:", df_clean.shape)

Before target cleaning: (9232, 37)
After target cleaning: (9232, 37)